---
version: "2.0"

services:
  app1:
    image: bsord/tetris
    expose:
      - port: 80
        as: 80
        to:
          - global: true
  app2:
    image: bsord/tetris
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 256Mi
        storage:
          size: 256Mi
  placement:
    akash:
      #signedBy:
      #  anyOf:
      #    - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        app:
          denom: uakt
          amount: 100

deployment:
  app1:
    akash:
      profile: app
      count: 1
  app2:
    akash:
      profile: app
      count: 1
