# Simple deployment.
---
version: "2.0"

services:
  app:
    image: bsord/tetris
    # command:
    #   - "sh"
    #   - "-c"
    # args:
    #   - sleep infinity
    expose:
      - port: 80
        as: 80
        to:
          - global: true
        #accept:
        #  - "tetris.yourdomain.com"


profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        app:
          denom: uakt
          amount: 1000000

deployment:
  app:
    akash:
      profile: app
      count: 1
